name: Rust

on:
  push:
    branches: '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install VideoStream
      run: |
        curl https://deepviewml.com/apt/key.pub | sudo gpg --dearmor -o /usr/share/keyrings/deepviewml.gpg
        echo 'deb [signed-by=/usr/share/keyrings/deepviewml.gpg] https://deepviewml.com/apt stable main' | sudo tee /etc/apt/sources.list.d/deepviewml.list
        sudo apt-get update
        sudo apt-get install libvideostream
    - name: Run tests
      run: cargo test --verbose

  rustfmt:
        name: Format
        runs-on: ubuntu-latest
        env:
          RUSTV: nightly-2023-07-01
        steps:
          - uses: actions/checkout@v2
          - name: Install
            run: |
              rustup toolchain install $RUSTV
              rustup component add --toolchain $RUSTV rustfmt
          - name: Check
            run: cargo +$RUSTV fmt -- --check
